[build]
target = "thumbv6m-none-eabi" # Uncomment for RP2040 builds
#target = "thumbv8m.main-none-eabihf" # Uncomment for RP2350 builds

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"

[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip RP235x"

[env]
DEFMT_LOG = "info"
